site.host=http://reploop.org
index.posts_per_page=1
index.paginate=true
render.tags=true
render.sitemap=true
img.path.update=true
asciidoctor.attributes=source-highlighter=coderay,coderay-css=style,coderay-linenums-mode=inline

