site.host=https://www.reploop.org
site.desc=REPLoop，在脚本编程语言中经常能看到REPL，也就是Read-Evaluate-Print-Loop，意思是读取源代码，评估执行，打印结果的循环。这个过程能够快速的学习实践然后得到结果。非常像一个学习成长的过程：输入信息，消化吸收，输出知识并用于实践，然后持之以恒的坚持。4个环节缺一不可，而且最难做到的大概是持之以恒了。
site.keywords=REPL,REPLoop,George,乔治
site.author=乔治
index.posts_per_page=3
index.paginate=true
render.index=true
render.tags=true
render.tagsindex=true
render.sitemap=true
relative.path.update=true
tag.sanitize=true
# default asciidoctor options
asciidoctor.attributes=graphvizdot=/usr/local/bin/dot
# Use local assets instead of third parties's
assert.cache.domains=cdnjs.cloudflare.com
