= 码农工作中的缩写词
乔治 <matrix3456@gmail.com>
2020-04-04
:jbake-type: post
:jbake-status: published
:jbake-tags: 缩写词
:idprefix:

码农工作中，如果经常看一些英文的文档，混迹于github上抄抄源代码，发发邮件交流的话，或者和早几年外企出来的人一起工作的话，可能经常能看到一些缩写词。不懂的人一脸懵逼，懂的人可能因为少打了几次键盘提高了效率而提前下班被领导白眼。
不过缩写词也就是习惯的问题，不是啥逼格的问题。

== 常用缩写词

RP:: pull request, 两个不同的代码仓库之间的合并请求。在分布式源码管理系统出来之后才有的概念，就是让别人拉取代码仓库变化的意思。
MR:: merge request, 提交代码前的合并请求。为了控制代码质量，有些代码分支不允许直接提交。 MR一般发生在向一个受保护的分支提交代码并请求评审代码的意思。
IMHO:: In My Humble Opinion. 也就是以我之见，恕我直言的意思。一般情况下是用于提出不同意见的。
TBD:: to be done，未完待续。意思是说一项工作应该要做，但是还没有完成。好多开源项目的文档中经常会看到。
WIP:: work in process, 施工/设计/处理/工作中，指一项工作正在进行中，还没有完成。开源中的Pull Request如果特别大，要分多次合并的话，每个Pull Request都可以加上[WIP]，说明还有后续的合并请求。
WTF:: what the fuck，类似国骂"我艹"之类的，语气词，大概就是这是什么玩意的意思。代码注释中经常能看见WTF的身影，愤怒的程序员。
FYI:: for your information，供你参考。一般是想把一个信息同步给另一个人，请他知晓的意思。
TL;DR:: too long, don't read，太长，别看，也就是长篇大论预警提示。一般是一个结论的详细说明，如果仅仅关注结论，不关心缘由的话可以直接跳过的。
LGTM:: looks good to me，看起来不错。代码评审中的同意的意思。
PTAL:: please take a look，请看一下我的提交。github上经常能看到，某个代码提交或者合并请求，需要某个人评审，就可以这么说。
SGTM:: sounds good to me，听起来不错。代码评审中的同意的意思，或者某项提议/设计方案不错的意思。
RTFM:: read the fucking manual, 先读一下手册。一般都是问题太简单，都写在手册里面了。
STFW:: search the fucking web, 先上网查一下。一般都是问题太简单，简单搜索就能找到答案。
W/O:: without, 经常在github的issue中看到w/o，勉强也可也算开发术语，w/o转化为without之后就简单了吧？


暂时写这么多，后面遇到新的在补充。