= 过于在意别人的看法，如何克服？
乔治 <matrix3456@gmail.com>
2020-05-09
:jbake-type: post
:jbake-status: draft
:jbake-tags: 成长,认知
:idprefix:

== d

[quote]
后来踏入咨询行业，接触了很多也是被过于在意别人的看法而困扰的来访者，我发现几乎是所有的这类人都有一个共同点：童年时总是被父母或抚养者要求成为他们所期待的人。

我不是这样的，我父母是农民，而我则读书出来在城市里干着他们认为“不用受苦”的好工作。这个过程中父母是支持的，但是也没有期盼成我现在这样，他们也盼不到，也没有说要成为他们自己那样的人。而且我在我们那个村范围内还是第一个大学生。我不太理解我为什么也非常在意别人的评价，听到正面评价我会脸红谦虚，听到负面评价立马觉得自己有问题？

[quote]
比如说你拥有了一群接纳你的伙伴、你在学校里成绩很好不断地从别人那里获得正反馈就形成了「无条件自尊」、你力气很大你们班的同学都很怕你等等，这些都是有可能改变我们的认知模式的外因。

我从小学到初中毕业大部分情况下都是我所在学些的TOP1，没有出过TOP3，高中也是中等偏上的水平。按说我应该有很多正反馈，但是还是没有建立起来

[quote]
我们必须意识到，去追究是谁的错、追究什么原因，这对我们的问题的解决，并没有任何的用处。
我们要做的只是针对问题，寻找解决办法，然后做出改变，问题就解决了。

不知道原因是否能对症下药找到解决办法呢？不要归因到人，归因到事情。就是可以归因到方法论，归因于决策逻辑，归因于信息输入不充分等等，但是一定不要上来就归因到人不行。

[quote]
这种恐惧来自于我们问题的触发因素：父母要求我们成为他们期待的人。在童年时期，父母是我们能够生存下去的唯一保障，得不到父母的认可，无法满足父母的期待，这就意味着我们有被他们抛弃的风险。而对于儿童来说，被父母抛弃，就意味着死亡。

害怕得罪人这个行为是有的，但是出发因素可能不是期待？或许是小时候看过父母发生争吵进而“打架”留下了这种“死亡危险”的恐惧？

[quote]
所以当一个不能够接纳他自己的时候，他的内心就是空洞无物的，他无法从自身内部获得支撑，而不得不从外界寻求认同和力量。


1.别人没那么在乎你，也没那么关心你。
 
虽然在文字的表述上是“太过在意别人的看法”，其实这本质上指的是“过度的自我关注”。
 
也就是说问题的实质根本不在于别人怎么看你，而是你自己将别人对你的看法看的太重要，将别人对你的看法所导致的后果看的太重要。
 
实际上你必须清楚地意识到这一点：并没有多少人在关注你，也并没有多少人对你有什么“看法”。
 
你想一想，你对别人又有多少的看法呢？即便是你对某个人有些看法，但这个看法又能持续多久？那么你的看法又会对别人造成什么影响？
 
你对别人的看法根本就没有什么实质性的影响，假如说产生了什么影响，那根本的原因也是因为那个人“在意”你的想法，所以他才会有所应对。
 
反过来在你身上也是同理，别人对你的看法这本身就是一种「非实质性」的影响。
 
所以你看：你因为害怕别人别人对你的看法所造成的影响——所以你才会在意别人对你的看法。
 
而如果你不在意别人对你的看法——那么别人对你的看法就不会对你造成什么影响。
 
你明白了？
 
看法始终只是看法而已。
 
 
而如果你说：那别人骂我是傻X怎么办？别人欺负我怎么办？别人排挤我怎么办？
 
那这就是关乎你“懦弱”的问题了，当别人对你产生「实质伤害」的时候，这就已经不再是「别人对你的看法」的问题范畴内，你要做的是捍卫自己的权利，去反抗欺负你的人，或者在的确是你很傻X的时候改掉你的那些愚蠢的做法。
 
我们要知道：太过在意别人的看法的对立面是「不在意别人的看法」，而不是「彻底的、绝对的、完全拒绝别人的看法」。
 
不在意只是意味着你不会被别人的看法影响，也不会被别人的看法伤害。但你仍然会正视，面对，并且接受别人对你的看法。
 
假如说是因为你在宿舍随地大小便这种过度的行为而导致了别人对你的不满，那么你要做的是修正自己的行为而不是无视别人的看法。
 
所以一个重要的前提是，你要能够在客观的层面上分清楚你的行为是否对别人造成了伤害或者影响，如果不违背法律和最基本的道德，也没有伤害或影响到他人，那么你才可以完全无视别人的看法。
 
 
2.对于你而言，在这个世上你自己才是最重要的。别人和别人的看法，都不重要。
 
每一次当我告诉我的来访者们“他们自己才是最重要的”时，几乎无一例外他们都会回答我：“这样也太自私了吧？”“可是我父母生养我很不容易啊！”“那她是我最好的朋友哎！”“可是我真的很爱我的男朋友啊！”
 
每当我听到这样的回答时，我都会忍不住在心底心疼这些人一把，看看「社会意识」已经把这些人伤害到什么地步了，他们竟然完全没有自爱自尊的意识。
 
在我们的社会环境中，始终在强调集体主义，强调助人为乐，强调要为别人考虑，我们将为自己的立场考虑、表达和满足自己的需求定义为自私，并且整个社会都在或明或暗的对“自私”持批判性的态度。
 
这就和为什么太懂事的孩子长大了往往不幸福的原因是一样的，一个人如果没有勇敢的、坦然的满足自己的“自私”的心态，而只会一味的照顾和满足别人的感受，那他将永远不可能获得幸福。
 
因为快乐的本质就是对自身欲望和需求的满足，你必须将自己的需求放在首位，你的整个人生基调才可能是幸福的。
如果你时刻想着别人，时刻去迎合与满足别人，你的需求和欲望就会被长期的压抑，久而久之，你就会忘了自己究竟想要什么，忘了自己喜欢什么，这个时候的你，本质上就和行尸走肉并无二异了。
 
无论任何一个人，他活在这世上首先是为了他自己。你这一生会不断地遇到许多人，会有无数的人随意的向你发表他们对你的看法。他们对你的看法重要吗？
 
事实上一点儿都不重要，现在你身边的绝大多数人都可能会在三年、五年后消失，对于你而言，这些人只不过是你生命中的一些过客而已，所以你有什么必要去奉承和讨好这些对于你一点儿都不重要的人？你有什么必要去在意这些过客们的看法呢？
 
你这时候可能会想：但我的好朋友/我的老公她们会陪我一辈子的啊，他们对于我而言是很重要的人呀！
 
没有错，这些人的确对你很重要，但重要和你要牺牲自己去迎合别人之间没有丝毫的关联。
 
这个人对于你很重要，但你没有必要“丧失自尊”的去迎合他。
 
更何况你也清楚，你和这些“重要”的人也许要共同陪伴一辈子呢，难道你愿意一辈子都在委屈自己去迎合他人吗？
 
从最根本的层面上来讲，别人根本一点儿都不重要，你活着本身就是为了你自己。如果你不能够为了自己而活，那么你这一生就相当于是枉过一生而已。只有为了你自己而活的生命，才是真正有意义的。
 
我可以告诉你的是：你完全有权利自私，你也天经地义的应该把自己放在首位。如果你选择尊重自己，不过度在意别人，你会活得轻松快乐很多；
如果你继续去迎合别人，继续去在别人面前“表演”，继续去试图成为一个别人所期待的人，你就会继续现在的这种痛苦。
 
你是要轻松地自私着，还是要痛苦的迎合着呢？
 
 
3.把你自己的需求放在第一位。不要委屈自己成全别人。
 
有太多太多的人不会、也不敢表达自己的需求，而这一点是非常普遍的造成许多人非常痛苦的原因。
 
他们会在无比愤怒的时候面对着伤害他们的人却无法骂出哪怕一句脏话，无法攻击对方哪怕一下，无法表露出哪怕一丁点儿带有攻击性的情绪。
 
他们仿佛天生就被训练的会去理解别人的立场，会去照顾别人的感受，会去满足别人的需求。
 
但是你想一想，又有谁理解了你的立场，谁照顾了你的感受，谁满足了你的需求呢？
 
你并没有任何的必要，也并没有任何外界的压力和束缚在令你不得不在意别人的想法和感受啊。
 
你说但是社会潜移默化的有很多规则，有别人会评判你。
 
问题是这些规则和评判对于别人而言也是一样存在的，为什么别的人就不会这么在意这些社会规则和别人的眼光呢？
 
归根结底还是在于你给自己套上了枷锁，你给了自己太多了限制，你不敢去迈出那一步，你把别人的眼光和评价看的太过重要了。
 
只需要尝试一次，只需要尝试一下不去在意那别人的看法，只需要尝试着满足一次你自己的需求，只需要一次，当别人惹恼了你的时候你骂出一句“你给我滚”，只需要一次，当你父母要求你满足他们的期待时你坚定的告诉他们：我自己的未来我自己做主。
 
只需要这一次，你试试看，自己会不会死，天会不会塌下来，你所幻想的那些恐怖究竟存不存在。
 
或者即便是你朋友愣住也和你生气了，你父母恨铁不成钢的说你太不懂事。
 
 
那又怎样呢？
 
 
所以为什么就不能够和他们争吵？为什么就不能坚持你自己的想法？为什么一旦别人反对你你就马上按照别人说的去做呢？
 
如果你因为“我说了他们不让啊”“可是他们不理解我”“我说不过他们”这种理由而不能坚持自己的做法，我只能说你的一切痛苦，完全是你自己在自作自受。
 
你自己的决定，别人让或者不让，别人理解或者不理解，别人说的多么有理，这和你有什么关系？
 
我问你，别人不让你吃好吃的，别人不让你去做你想做的工作，别人不让你和别人起冲突，凭什么？
 
别人有什么资格控制你？
 
或者说，你为什么要按照别人对你的要求去做事情？
 
他不让就让他不让去，他不理解就不理解呗，他说的有理就让他有理，他不接受就让他不接受。
 
你自己的决定，关别人屁事？
 
 
4.不要害怕得罪别人。
 
我知道看到这里很多人会担心：但我要是真得罪了别人，那怎么办？
 
你要意识到：不害怕得罪别人不意味着你要刻意去得罪别人啊。不害怕只是说即便发生了冲突，你也会去面对这个冲突，即便别人不开心，那就让他不开心去。而不是刻意找茬，刻意去得罪别人。
 
对于现在的你而言，你会因为害怕得罪别人而刻意小心翼翼的去注意自己的言行举止，会为了和别人不起冲突而压抑自己，会为了不让别人对你产生不好的看法而去为别人的错误负责。
 
而不害怕只是让你放松下来，让你回到正常人的程度，不会故意惹事，但如果出现了冲突，就要就事论事，是你的错误，你承担；不是你的错误，就绝对不会去忍受。
 
所以虽然在语言的表述上是：不要害怕得罪别人。而本质其实是：能够就事论事的分清问题的边界。
 
如何分清责任边界，详见我的这篇文章：分清责任边界|每个人只能为自己负责
 
 
5.放弃“成为更好的人”“努力变得更优秀”的这种幻想。
 
好的，坏的，对的，错的，这些都不重要。你想要的，才是最重要的。
 
没错，我在建议你放弃变得更好，放弃努力，放弃变优秀。
 
而且试图变得更好，试图变得更优秀，试图变得更成功的这种信念是导致你的痛苦和不幸福的一个很重要的根源。
 
整个社会，整个人类世界都在推崇和鼓励你要去努力，要变得更好。
 
于是你开始对自己不满意，你开始讨厌自己，你开始强烈的不能接纳自己。
 
于是你开始自我否定，开始去追逐社会规定的那些优秀的定义，开始试图去迎合别人的看法，你因此变得很焦虑，你被对自己的不满和自己驱使着不断地向前走，你以为只要达成那些目标你就能轻松了，你就到达终点了，你就圆满了。
 
但是这一刻却始终不能到来，而你却一直被一种焦虑感控制和驱使着，这样你变得越来越着急，你觉得必须尽快到达那个终点，只有到达那个终点，只有变得更优秀了你才能不再这么焦虑，于是这种着急和焦虑会令你变得越来越浮躁，你会发现你离那些目标越来越远。
 
而有那么一些人即便是侥幸到达了他所自以为的那个终点，但到达的那一刻他却发现自己好像并没有体会到想象中的那种喜悦和满足，他也并没有放轻松，焦虑与痛苦始终还是如影随形。而他这个时候所体会到的很可能只是一种无边的空虚。
 
所以你有没有想过，追求外界的标准，追求别人的认可与赞同，追求变得所谓的“更优秀”其实一开始就是一条会伤害你的道路呢？
 
马斯洛提出人有五种需求，最高层的需求叫做自我实现。
 
这个「自我实现」指的就是「做“你自己”想做的事」「完成“你自己”的使命感」「追求“你自己”存在的意义」。
 
而你一直在试图满足“外在”的标准，这和你的本能需求无疑是背道而驰的。
 
真正的进步与提升是你基于接纳自我的基础上去完成你的目标，满足你的需求，你只是想做这件事情，仅此而已。
就像你吃一份你喜欢的冰淇淋，画一幅你想画的花，追一个你爱上的姑娘一样，这都是非常自然而然的事情，而不是为了达到一个怎样的标准，能够给自己贴上一个“优秀”或“厉害”的标签。
你也不会着急，充满焦虑，为了填补匮乏和焦虑而不停地催促自己，你会完全的放松，不疾不徐的按照你的节奏去做事，去生活。
 
成为“你自己”，而不是成为“优秀或卓越”，这才是自我实现的涵义，这也是你存活这一世的根本意义。
 
我相信看到这里，你的认知层面已经受到了一定的冲击，你也能够对你现在的看待你和别人的关系的方式有了一定的反思。
 
但是核心信念的改变，也只是停留在认知的层面上。知行合一，才能真正将你的问题解决。
 
对于你要在行动层面上做出的改变，我给出你如下的建议：
 
 
1.将你所在意的别人对你的看法记录下来，然后尝试着去做出不被别人的看法所影响的行动。
 
“过于在意别人的看法”这本身是一个意识层面的问题。
 
别人对你有看法，这是一个客观事实，你改变不了。你很在意别人的想法，这对于你的意识而言，也是一个客观存在，我们短时间内可能没办法一时将其消除。
 
但是你可以控制的是你自己的行为和做法，你要做的就是，即便你的意识层面很在意别人对你的看法，但你的行动层面依然能够不受其影响。
 
比如说，小赵认为你扎丸子头不好看。你以往的做法是就不扎丸子头了。而你接下来要练习的就是继续扎丸子头。
 
我知道对你来说很难，但克服这个困难本身就是你成长的过程。你要做的本来就是要去克服自己的心理障碍，而不是把这些困难和心理障碍和困难当成你不去做事情的理由。
 
你要记得，你不做某件事的理由只有两个：一个是你不想，一个是不可能完成。
 
困难不在这两者之内，当你尝试着克服一次这种不敢扎丸子头的恐惧时，你就已经是在客服“太过在意别人的看法”这个问题了。
 
 
2.尝试着与别人起最少三次的冲突，并绝对的坚持你自己的决定，而不被别人说服。
 
我知道绝大多数的人看到这个练习都会本能的抗拒而不会去做。
 
但不需要过多的解释，只要是能做去尝试这个练习的人，就一定能摆脱过于在意别人的看法的问题。
 
 
3.尝试表达出自己的需求与感受。
 
“我没有时间帮你”
“如果你不能够像一个朋友一样尊重我，那我也没有必要去尊重你”
“在我小时候你们伤害了我很多，所以不要再继续试图控制我，我不要再去任由你们摆布，今后我要过自己的生活”
“我希望你能够多关注我，多陪陪我”
“你要求我理解你，但为什么你却并没有理解我？即便是我理解你，但你对我造成了伤害，我就有权利拒绝你”
“别他妈的再对我评头论足，我他妈想做什么是我自己的事，和你们这帮傻X有个鸡毛关系”
“不”
 
是不是有好多类似于这样的话在你的心中憋了好久了？但每次总是非常难以把这些话说出口？
 
其实你知道自己的需要是什么，或者说最起码的，你肯定知道自己不想要的是什么。
 
你只是难以拒绝，不敢拒绝，也不会拒绝罢了。
 
那么你接下来要练习的，就是把这些你以往不敢说的话痛快的说出来，你要做的是不再委屈你自己，不再去照顾和体谅别人，不再被别人所控制，而是明确你的界限，捍卫你自己的立场，将你自己先保护好。
 
很多人说找不到、不知道自己想要的是什么，但你只有能够坚定的拒绝那些你不想要的，你才能够坚定的维护好那些你自己所想要的。
 
寻找自己真正想做的事，追求自我实现，这本身就是一件非常难的事情。你可以先从拒绝自己不想要的开始做起，拒绝的多了，那些你想要的，也就会慢慢的明晰。
 
 
《明朝那些事儿》最后说：这世上只有一种成功，就是用你喜欢的方式度过一生。
 
这句话对我的影响一直重大而深刻，在许多年的生存，工作，搬迁，交际，追逐，选择的过程中，这句话始终在提醒着我：你活着是为了你自己，你对于自己负有完全的责任。金钱也好，名声也好，地位也好，这些都会诱惑和吸引着你的“社会我”。但你始终要记得，你不是社会的奴隶，你也不是社会的工具，你更不是社会的一个零件。
 
归根结底，活着就是三个字：
 
做自己。

以上。
