= 小学数学在工作中应用
乔治 <matrix3456@gmail.com>
2020-05-04
:jbake-type: post
:jbake-status: draft
:jbake-tags: nginx,配置文件,优先级,优化,location
:idprefix:

作为一个Java程序员，干Web相关的开发，除去具体的业务，实质上干的就是通讯的工作，通过网络在不同机器之间来回搬字节（byte）。这么一比较，Java Web程序员的工作某些部分其实和大街小巷里面穿梭的快递员有几分相似。

回到正路，日常工作中经常会碰到一些数字，需要给出合理的数值。这些数字可能是垃圾回收（GC）的频率，内存（Heap）的大小，线程池（Thread Pool）的大小，对象池（Object Pool）的大小，网络超时（Timeout）时间，压缩阀值等等。都是些应用层的东西，再往下深入到操作系统，协议层面的东西不知道小学数学还适用不适用了。

== GC的频率

GC的频率与内存的大小息息相关，如果一个JVM的应用不正常，首要查看的可能就是GC状态。GC，尤其是FGC频繁一定是JVM目前不在正常状态，但是反过来不见的是成立的，这还要取决于你对频繁的理解。



== 线程池的大小
xref:how-to-size-thread-pool.adoc[线程池]

== 对象池的大小

== 网络读超时（Read Timeout）时间

从开始读数据到读到第一个字节的最长时间，超过这个时间，客户端就会报一个Read timeout异常。 Specifically, if the server fails to send a byte <timeout> seconds after the last byte, a read timeout error will be raised.
http://stackoverflow.com/questions/3069382/what-is-the-difference-between-connection-and-read-timeout-for-sockets

== 网络连接超时（Connection Timeout）

三级握手完成时间

== 请求超时（Request Timeout）

Connection Timeout + Read Timeout + Data Transforing Time

== 压缩阀值

== 稳定性
