= 分布式系统中的一致性模型
乔治 <matrix3456@gmail.com>
2021-12-25
:icons: font
:jbake-type: post
:jbake-status: draft
:jbake-tags: 分布式系统,一致性模型,可见性,原子性,MVCC,事务,隔离级别,数据库
:idprefix:

一致性模型经常挂在嘴边，但是直接给出一个一致性模型图，又不知所云，说不出一个所以然来。image:http://jepsen.io/consistency/models/map.svg[c,340]

== 数据操作

对于数据的操作，最基础的就2个：读和写，没有其他的了。其他操作都是为了性能或者使用的便利性而组合创造出来的，这是一个粒度从细到粗的方向从底层的读/写一直上升到应用开发者使用的SQL，RESTfull API以及RPC等等。

=== 单机操作

以CPU为计算核心，基于寄存器的计算机，对数据的全部操作就是读，写寄存器了。 想象一下指令不断的被CPU执行，CPU所做的操作就是读取寄存器数据， 计算并修改数据， 把结果重新存储到寄存器中。

数据以及存储本身不会修改数据，反而是要做到数据的正确持久存储。所有的变化都是通过CPU计算作出的。这就是read-modify-write基本动作了。 针对数据、寄存器、CPU缓存或者内存，最基本的操作就是读(read)与写(write)，而计算(modify)是CPU的工作。

这时候的数据，有两个特别重要的特征：

可见性:: 数据变化其他进程能不能，什么时候看见这个数据。
原子性:: 看不到数据修改的中间状态，也就是要不是修改前的数据，要不是修改完成后的数据，一定不会是中间状态的数据。这种中间状态的数据也叫做**脏数据**。

=== 分布式系统操作

单机的进程是按照**地址**来访问数据，而分布式系统中则是按照**属性**来访问数据的。这个属性可能是一个唯一ID，也可能是姓名或者多个属性组合起来的。我们可以属性或者属性的组合统称为key。 更进一步你可能听说过数据库的存储引擎可以是一个KV系统。所以分布式系统中的读操作就是``v=read(k)``，写操作就是``write(k,v)``。针对关系型数据库，k由where子句定义，v有可能是唯一的，也可能不唯一；同样的写操作也是类似的可以影响一行或者多行记录。

== 基本概念

分布式系统::
一个部署在多个机器上并通过网络连接到一起的，彼此之间共享数据的一个系统。

一致性模型::
一致性模型描述的就是多个进程读/写多个数据，一段时间之后这些数据的可见性和原子性等特征是什么样子。一致性模型常用来描述分布式系统的。

事务::
事务通俗理解就是让多个操作组合起来的复合操作像一个单独操作一样，要不全部生效，要不都不生效。复合操作对数据的影响：对于单个事务，对数据的操作要不全部生效，要不都不生效。对于多个事务的并发与事务之间相互的影响，不同的场景有不同的要求，演化出不同的隔离级别。事务常用来描述部署在单个机器上的单个系统的。

分布式事务::
事务由单机系统扩展到在分布式系统中，事务的理解本身没什么变化，只是事务作用于一个分布式系统，而非单机系统了。

事务的隔离级别::
SQL-92标准中定义了4个隔离级别，按照隔离级别由低到高依次为：
- 未提交读(SERIALIZABLE)
- 提交读(REPEATABLE READS)
- 可重复读(READ COMMITTED)
- 序列化(READ UNCOMMITTED)

== 参考

* Microsoft, https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/transaction-isolation-levels?view=sql-server-ver15[Transaction Isolation Levels (ODBC)]
* JEPSEN, http://jepsen.io/consistency[Consistency Models]
