= 基于Cookie的多站点单点登陆(SSO)方案
乔治 <matrix3456@gmail.com>
2024-07-28
:icons: font
:jbake-type: post
:jbake-status: published
:jbake-tags: 单点登陆,SSO,Cookie
:idprefix:

单点登陆在一个用户存在与多个服务中的时候用来增强用户访问体验，免去了多次重复输入账号和密码的麻烦，同时在登陆的情况下也在不同服务之间跳转更丝滑而没有因为跳到登陆页而对访问造成不必要的打断。

用户登陆基本上是一个向服务证明你是你的过程，一旦你通过用户名和有且只有你自己知道的密码证明了你就是你之后，服务会给你一个凭证，在随后的访问过程中只要带着这个凭证服务就认为是你在访问而不需要在重新鉴权。

这个凭证在不同的场景下有不同的做法，常见的比如浏览器中的Cookie, oAuth中的Access Token或者JWT等等。对于Web服务，基于浏览器的__https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Cookies[Cookie有安全机制]__，比较适合作为用户登陆凭证的持有机制，当然其他的方式也自然有其应用场合。

== 单站点登陆

一个站点的登陆比较直观，用户从登陆页出入账号和密码之后，服务端校验通过之后创建一个会话(Session)保存在服务端，然后将这个会话的ID通过Cookie的方式设置到客户端浏览器。这个会话ID就是你的登陆凭证。登陆成功之后，所有的本访问都会通过Cookie的形式带着这个会话ID给到服务器端，服务器端通过这个会话ID去查找是否存在一个会话，并且从会话中得知当前登陆用户是谁。

用户登陆只需要输入一次用户名和密码即可。登出也比较简单，直接删除会话即可。

== 多站点非SSO登陆

当一个用户可以访问一家公司的多个服务站点的时候，就会出现用户注册一次想再多个站点之间共享。这样对用户和公司的不同站点都便利。这时候用户如果在不同服务站点之间跳转，涉及到鉴权的时候可以用最朴素的办法用同样的账号和密码登陆多次。这样对用户非常不友好，繁琐的同时还浪费不必要的时间。该SSO派上用场了。

此时用户如果要登出的话，不能直接做到一个站点登出之后所有的站点都统一的登出。毕竟登陆都是一个一个登的，登出一个一个登出实属自然。

== 多站点SSO登陆

涉及SSO的时候，我们用一个单独的SSO登陆站点来登陆。当用户在未登陆的情况下访问站点A的时候，站点A将用户引导到SSO登陆站点让用户登陆。用户在这里输入账号和密码进行登陆鉴权，成功之后同样会创建会话及其ID以Cookie的方式返回到浏览器，同时将用户跳转到站点A，跳转的过程中携带一个一次性的令牌(Token)到站点A，这个Token和本次登陆的会话是关联的，但不能是会话ID本身。

站点A随后发起一个Token鉴权的请求到服务端，服务端拿着这个Token去SSO登陆站点服务校验是否存在，通过后同时也能从此Token关联的会话中得知当前登陆会话的ID，并且返回到站点A的服务端。站点A的服务端此时也创建一个会话，并且将SSO站点的会话ID以及当前登陆用户的信息存储会话当中去。

当用户访问站点B的时候，站点B将用户跳转到SSO登陆站点之后就能正确的识别出用户的登陆状态，免去了重新认证的过程，同样是返回一个一次性的Token将用户跳转回站点B并创建会话和设置Cookie完成登陆。

在任意一个站点登出的时候也是直接调转到SSO登陆站点去登出，删除其在SSO站点的会话。

整个过程和oAuth的Authorization Code Flow非常接近。只不过SSO这个过程是基于浏览器的Cookie来保存会话ID的，整个过程用户不需要接触这个会话ID。

=== 会话管理

这个主要是会话过期时间的更新. 一般情况下只要用户有活动，像服务端发送了请求，此时就应该更新会话的最后访问时间，以及重新设定会话的有效期为新的有效期。



== 参考

* What Is Single Sign-On Authentication (SSO) And How Does It Work?, https://auth0.com/blog/what-is-and-how-does-single-sign-on-work/
* HTTP Cookie, https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Cookies