= 研发环境的设计思路
乔治 <matrix3456@gmail.com>
2022-04-24
:icons: font
:jbake-type: post
:jbake-status: published
:jbake-tags: 公司,经营,商业,效率
:idprefix:

为了团队协作和系统稳定，一般公司的研发环境至少会分为：**开发**，**测试**和**线上**。这个大概是开发下意识就会有的基本思路。

从系统稳定性的角度，开发人员可以随时谁地变更开发环境，稳定性最差；测试环境供测试团队使用，或者研发之外的产品，运营团队来测试，验收，要有一定的稳定性；线上或者生产环境是面向真实用户的，稳定性要求最高。对线上环境的变更需要有一定的流程和规范。有些在上线之前还可以有一个预发布环境，此环境是一个准生产环境，使用的资源都是线上的资源，只是服务入口对用户是隐藏的，一般是上线前内部评审使用的环境。这个功能也可以用测试环境代替，但是一般测试环境数据没有线上规范，可能会有部分效果看不到。

从用户的角度，环境可归类为线上和线下两部分。线上环境包含生产和预发布环境，线下环境包含开发和测试环境。开发者一般都需要本机开发调试，所以开发环境又可以多一个本地(local)环境。

最后可以组成一个**本地**，**开发**，**测试**，**预发布**和**生产**5个环境。视团队规模酌情全部使用，或者简化省略一部分环境。最简单的就是维护一个生产环境，开发直接变更生产环境，只是从团队协作和业务稳定的角度看风险非常高而已。

从团队协作的角度，通常会有涉及**开发**，**测试**，**运维**，**产品/运营**到最终的**用户/客户**。 不同开发之间的工作最好不要互相影响，不同测试之间的工作也不要影响。同时开发最好也不要影响测试工作，反之亦然。因此我们可以在**一个环境内细分为多个分组（shard/group）**，分组之间可以共用一部分环境，但是在不同分组之内各自变更的部分是相互独立而不干扰。比如线上环境如果要支持A/B测试的话，那么也可以分为2个组，一个测试组和一个对照组。不同的开发按照不同的功能(feature)为组各自独立开发和测试。比如一个支付团队在迭代支付服务，电商团队在做购物车的迭代，购物车流程是要用到支付服务的。这时候电商团队和支付团队就可以在开发环境中分别为两个功能分组，各自开发，而不会因为支付团队也在开发状态而影响电商团队的迭代开发。

[graphviz]
----
graph ENV {
    online[label="线上"];
    offline[label="线下"];
    dev[label="开发"];
    test[label="测试"];
    prod[label="生产"];
    local[label="本地"];
    pre[label="预发布"];
    A[label="A/B" shape="box"];
    B[label="A/B" shape="box"];
    S1[label="分组1" shape="box"];
    S2[label="分组2" shape="box"];
    S3[label="分组3" shape="box"];

    online -- { prod; pre};
    offline -- { dev; test };
    dev -- { local };
    prod -- {A;B};
    test --{S1;S2;S3}
}
----

每个环境尽可能的保持一致或者相似，然后通过性能指标来调整资源分布，从而保持一致或者相似的前提下避免资源浪费。这样研发人员对各个环节会越来越熟悉，对于故障处理等紧急情况下的效率有很大的帮助。

== 隔离

区分环境主要是为了隔离，包括代码，数据库，消息队列，应用，负载均衡，基础设施比如机器以及网络环境等。还需要考虑依赖的第三方应用对环境的兼容性，比如第三方支付通道如微信支付不存在测试，应用要测试就是用微信支付线上的环境，线上的商户，线上的签名配置等。

=== 物理隔离

这种隔离使用的是不同的物理机器，不同的部署服务，不同的代码仓库，不同数据库等等。这是物理级别的隔离，颗粒度比较粗的方式。

=== 虚拟隔离

不过随着虚拟化和容器化，以及云原生的趋势，很多物理资源都可以共享里。

基础设施： 容器，云服务

构建一套服务，环境 数据的路由功能也是可以用来做隔离，虚拟隔离。

一切都可以基于tag来设计： tag protocol设计方法 典型如TCP 协议栈

=== tag的方式：

- 域名方式：tag.domain.com
- HTTP Header: x-shard or group
- HTTP cookie/query parameters: 传参数的方式
- tag metadata:数据以及附带的元数据。

整个过程拆分为三步：代码-构建-部署。而且过程中代码和构建分离，代码和环境的分离，最后统一部署。

- 代码只关注业务逻辑，不用操心部署环境；
- 构建服务将根据目标环境构建可部署的包；
- 部署服务交给专门的CD部署系统来统一规划；

== 环境与分组（sharding）

- 每个feature都可以作为一个环境，
- 重要基础设置的共享：测试环境数据库是不是要每个feature一个呢？如果不需要，那该如何在不同的feature之间共享

=== fallback机制

每个环境都需要有一个默认的分组，如果没有指定分组的话，可以使用默认分组。但是环境与环境之间是严格隔离的。就是开发环境严格的不能使用测试的数据库，更不能链接线上的数据库。

测试数据的规范和覆盖率 数据不完备或者不规范，导致很多逻辑验证不规范，覆盖率不到。会导致很多的时候测试环境没问题，一到线上就有问题的现象。线上数据脱敏之后定期同步到测试环境。

=== 命名服务

把资源先按照环境划分，每个环境在按照分组划分，然后形成对于的名字。

分组-环境-资源

shard.env.resource
