= “程序员”的成长之路
George Cao <matrix3456@gmail.com>
2020-01-29
:jbake-type: post
:jbake-status: published
:jbake-tags: 鸟哥, 程序员, 成长
:idprefix:

[abstract]
本文系2017年11月25日“鸟哥”的题为《“程序员”程序员成长之路》的分享结合自身的理解整理而来。这个分享PPT如果硬要规个类别的话，那就是乔布斯或者老罗说相声的PPT的样子，一页上只有一行字，其他的全靠嘴上功夫，然而就这样随性讲了2个小时，过程中轻松愉快，也不乏启发思考的点，是小白个人比较喜欢的风格。

== 分享环节
=== 鸡汤有毒
开场白是鸡汤有毒，明确表达了很少做非技术类的分享。对待鸡汤应该持有的态度是评判性的，要有能力甄别信息。
过程中也是提出观点，让听众自己思考。

=== 要有“野心”，并且要让其他人知道
这里的“野心”说的是你短期或长期的目标。每个人都有自己的“野心”，只是有些人表达出来了，而有些是羞于表达的。比如最实际的一个目标是你想不想1年后工资涨50%？我相信每个人心中都有过这个想法，你也可以把他确立为你的短期目标。等目标明确了之后，要让其他人知道。因为其他人往往不知道你想要什么，之后就为这个目标去努力。

=== 排除干扰
每天困扰你的问题，也就是干扰项，要有意识、有目的、有手段的去消除。鸟哥本身对物质享受要求高一些，08年毕业后加入雅虎后月薪7000左右，但是租房就花了3000左右，头2个月还是挺好的，第三个月补交了前2个月的各种税和费之后，竟然不够交房租的了。核心部门核心业务3.4个月，目标明确的去了百度系统部，解决钱少的问题。

毕业5年非常关键，干扰少，能迅速的提升。技术是一通百通的，学习思考的方法，而不是具体的技能。内向与外向：遇到挫折后自己静一静想办法解决的为内向，到处找人吐槽寻求帮助的为外向。

=== 舒适区，对自己狠一些。
懒惰是天性，需要有目的的把自己往一个方向上逼。

=== 通过事提升人
认真对待每一件事，不管做什么事，要做完美。追求卓越之后，一定有提升。横向业务的人资源比较充足。业务线的人都是比较紧张的。鸟哥本人西交大计算机，然后国际关系学院。为了做鸡头走向php，国内没人做，差异化，走出了名头。

=== 建设影响力
影响力决定了资源能不能向你靠拢，积极主动的去建设影响力。影响力：帮助了多少人决定了你的影响力。做的事情多，想问题的方面多，思考问题的角度多一些，所以成长快。鼓励大家多做分享，不要怕说错。

=== 为机会提早准备
时刻学习。

=== 修身养性
教主原来是个死胖子，然后每天早上去健身，坚持了2年了。为了能够早上健身，还特意再健身房附近租了房子。

== 问答环节
1. 如何看人工智能？
笑称：人工智能是人工智障。拐点：机器可以开始自我学习的时候。但是未必会出现，不确定。现在是人机交互和图像识别做的好，整体还是挺傻逼的。

2. 精和广该如何选择？精度和广度是矛盾的，二选一。先精以后，以后学习总结到一套抽象的认识，然后以这为根据地往广度拓宽会比较容易一些。

1. 技术转管理的困惑：
团队的技术效能最大化，管理方法千人千面，自己摸索。自己的成就感来源要变。

2. 百度的经历：我一直努力让自己被更多人知道。

3. 精英创业与草根创业：自己的定位清晰。

4. 架构师的关注？全面了解系统的各个组成，懂得权衡，引进业界优秀方案，找到对业务合适的系统组成方式。

5. 大公司完善体系，如何提升？核心点还是自己的目标要明确，明确了之后办法自然就有了。

5. 牛人？正真的牛人是解决问题的。

6. 副总裁与架构师怎么平衡的？技术是乐趣，更喜欢程序员的称呼。做事是目的，想做的话什么事都能做好。

7. 机会争取的事情，蝴蝶效应：一定要争取

8. 语言：facebook来源具有玩票性质。需求是工具，重要的是解决问题的方法

9. 面试的时候提问一些题外话是不是需要了解的？明确目标，不管是什么困难都迎难而上，面试让你不懂什么，想去就学习。

10. 技术晋升：业务复杂，解决方案，评审的时候看的是能力，而不是做过什么。遇到了什么问题(突出难点)，我的解决方案是什么(列举一些，要有对比，说明优劣)，最后取得了什么效果。
