= Java日期与时间的一些理解
乔治 <matrix3456@gmail.com>
2021-04-22
:toc:
:icons: font
:jbake-type: post
:jbake-status: draft
:jbake-tags: 日期,时间,时区
:idprefix:

https://docs.oracle.com/javase/tutorial/datetime/overview/index.html[Java日期设计] 与 https://www.journaldev.com/2800/java-8-date-localdate-localdatetime-instant[Java日期API]

== UTC与GMT

[quote,firstname lastname,https://phrase.com/blog/posts/how-to-get-date-time-in-utc-or-gmt-in-java/]
____
To begin with, GMT (which stands for Greenwich Mean Time) is not the same as UTC (which stands for Coordinated Universal Time):

GMT is a time zone used in some but not all parts of the world (mainly Europe and Africa).
It uses either a 24-hour format or a 12-hour format for display and its based on astronomical observations.
UTC is not a time zone.
It is a standard which we can use to display time zones.
It is more stable as it takes time from an atomic clock.
____

[quote,323,https://stackoverflow.com/questions/46093200/showing-correct-time-from-milliseconds-with-desired-timezone]
____
But the concept is the same - those values are "absolute": they are the same for everyone in the world, no matter where they are.
If 2 people in different parts of the world (in different timezones) get the current timestamp at the same time, they'll all get the same number.
____

https://www.worldtimeserver.com/learn/utc-vs-gmt/



GMT+8 是时区， UTC+8不是时区，是一个offset，一个offset不能自动转为时区。Java语言中TimeZone.getTimeZone() 是按照时区去检索的，检索不到的话就是默认为GMT时区，这就和GMT+8差了8个小时了。所有GMT+8 不能用UTC+8代替。

== 默认时区

现在基本上容器是必须要支持的运行环境，也就是有可能环境不再是私有的物理环境，不受开发中控制的情况也经常发生。比如你使用了公有的镜像之类的。这种不受开发控制的环境，就需要通过外部参数来控制系统默认时区。其中的一种做法是通过系统属性 *user.timezone* 的方式在JVM启动的时候来设置：

.启动参数设置系统默认时区：
[source,shell]
```
java -Duser.timezone=Asia/Shanghai Main
```

其他方案参考这篇 https://www.baeldung.com/java-jvm-time-zone[文章]。

== Locale vs Timezone

Locale是指所属的地区以及该地区的语言，而Timezone则是时区。 直觉上我们一直说的是中国的时区是东八区，所以在系统层面就理解地区和时区之间是有关系的，也就是设置了Locale则自动设置了该地区的时区。其实他们两个之间是相互独立的。Locale作用于系统语言，比如国际化等。 TimeZone作用于日期和时间。 如果时间的字符串中有特殊语言，则可以使用Locale让系统知道。

Date， LocalDate，LocalDateTime 本身都是时间的结构化表达，本身并不带有时区信息。只需要需要给人展示的时候，才会用到时区信息来具体展示时间。

== 毫秒数

milliseconds 是一个绝对值，也就是同一时刻全世界不同地方同时通过

[source,java]
```
System.currentTimeMillis();
```

获取到的毫秒数是一样的。