= 如何讨论一个问题？
George Cao <matrix3456@gmail.com>
2020-09-05
:jbake-type: post
:jbake-status: draft
:jbake-tags: 认知,视角,变化
:jbake-lastModifiedDate: 2020-09-05
:idprefix:

如何和不同的人讨论一个问题？尤其是两个专业领域不同，背景不一致，坐下来讨论一个共同问题，并最终达成共识，然后在后续的执行过程中能够达到预期的结果。

== 视角

从创业公司层面的角度来看，做一个决策可能涉及到的考虑因素有：

* 市场
* 运营
* 品牌
* 技术
* 财务
* 公司
* 文化
* 认知
* 用户
* 需求
* 产品
* 经济
* 宏观
* 行业
* 人力
* 商业
* 管理
* 人性
* 信仰

暂时不讨论他们之间的关系，也不把他们归类，只是把他们列出来看看。在这种情况下针对一个问题开始讨论了, 讨论的目的当然是要作出各方都认可的决策。那么可能发生的讨论过程是这样的：

* 你按照市场决策，他说财务是关键。
* 你按照技术决策，他说市场不等人。
* 你按照品牌决策，他说产品更重要。
* 依次类推。。。

这种场景最常见的就是某一个领域的下属和横向业务上的领导讨论问题时发生，最后屁股坐的正的说就这么办，之前的讨论就结束了。

到了执行环节，下属将信将疑的免强做了动作，最后结果一会报上去，领导不满意，还说你不专业。结果变成一个双输的局面。

== 分析

人们常说

[quote]
唯一不变的就是变化。

我个人认为套用在和人相关的事情上都可以。如果你认同这句话，那就是要时刻准备接受变化，比如你读了更多的书，做了更多的项目，和更多的人接触，写了更多的代码，吃了更多的垃圾食品等等。现在让我们回到主题上了，这些变化会影响你看问题的角度，也就是会影响你作出决策，也就是之前的结论会变的。
剩下的问题就是变化有多快的事情了。

假设 stem:[x] 为视角，stem:[w]为视角的权重。那么讨论问题做出决策就可以表达为下面这个公式：

[stem]
++++
f(x) = sum_(i=1)^n w_ix_i
++++
其中的权重制约关系为：
[stem]
++++
1 = sum_(i=1)^n w_i
++++
所以变化部分其实就是某个视角的权重是变化的，各个视角的权重分配是动态变化的。所有人是变化的，

== 结论
讨论一个问题，可能从量变与质变，定量与定性，过程与结果等等多角度思考。
