= 复式记账
乔治 <matrix3456@gmail.com>
2022-03-03
:icons: font
:jbake-type: post
:jbake-status: draft
:jbake-tags: 会计,记账,复式记账,beancount
:idprefix:
:stem:
:eqnums:

[source,bash]
----
bean-extract config.py 微信支付账单_xxx.csv/alipay_record_xxx.csv > xxxxxxx.bean
----

*Notice:The raw data filename can only start with "微信支付账单" or "alipay_record."*

可以阅读[用于支付宝和微信账单的Beancount Importer](https://blog.sy-zhou.com/%E7%94%A8%E4%BA%8E%E6%94%AF%E4%BB%98%E5%AE%9D%E5%92%8C%E5%BE%AE%E4%BF%A1%E8%B4%A6%E5%8D%95%E7%9A%84beancount-import/)，了解更多细节。

* 账单： 记录资金从一个账户转移到另一个账户。每一个**交易**记录中，必然有一个账户是属于你的。
* 退款：支出流程的逆向流程。一般是原路返回，微信支持退回零钱。
* 部分退款如何记账？
* 收入：资金从别人的账户转入到你自己的账户。只关乎资金的流行
* 支出：资金从你自己的账户转出到别人的账户。只关乎资金的流行


== 特殊场景

- 借钱
- 垫付
- 报销
- 折旧
- 红包

复试记账每一笔都和自己有关。所以能区分出具体的用途。

收入在复试记账里面怎么理解？

== 复式记账

- 单式记账
- 复式记账

== 会计恒等式

资产(Assets) - 负债(Liabilities) = 权益(Equity)

[stem]
++++
Assets - Liabilities = Equity
++++

权益可以经一步细分为：初始资本(Capital)、收入(Income)和支出(Expenses)三部分。关系如下：

[stem]
++++
Equity = Capital + Income − Expenses
++++

整合一下上面两个公式，我们得到了：

[stem]
++++
Assets - Liabilities = Capital + Income - Expenses
++++

在这个公式里面，我们还是用Equity来表示初始资本(Capital)，则公式最终为：

[stem]
++++
Assets - Liabilities = Equity + Income - Expenses
++++

到这一步的时候，上面3个公式都很直观，符合会计知识的，也比较符合现实情况。值得注意的是上面公式中的数值都是**正数**。后面在使用Beancount的时候会出现把人绕晕菜了的**负数**。

既然都是正数，那么资产、负债、收入、支出或者权益的增减怎么表达呢？会计上使用**借记**和**贷记**。

== 借记和贷记

借和贷是站在银行角度来讲的，你的钱存入银行，相当于银行借了你的钱，对应银行的应付账款，银行记入借方科目。 如果你用的是信用卡，则是你借银行的钱，也就是银行贷款给你，对应银行的应收账款，银行记入贷方科目。 这样就形成了借记卡和贷记卡的叫法。 而**借**和**贷**在会计中逐渐的分别引申为账户余额的**增加**和**减少**。

稍微做一下数学中等价变换，得到了下面这个公式：

[stem]
++++
Assets + (-Liabilities) + (-Equity) + (-Income) + Expenses = 0
++++

== 复式记账

记账之前先了解一下交易。 经济里面说的一个人的支出是另一个人的收入，反之亦然。这是通过两两之间"等价交换"的方式来实现的，这就是交易。一笔交易会涉及2个主体，多方交易最终也是由两两之间交易构成的。记账就是记录交易。

=== 单式记账

单式记账是以账户拥有着的**账户**视角，记录账户余额随着交易的发生而产生的变化。 这里面只涉及一个账户，比如说你行用卡账单，就是信用卡这一个账户的**流水账**。如果你有多个银行卡，每个银行卡的账单之间是没有关系的。如果说有关系，那也是通过备注等描述信息标注出来的。

=== 复式记账

复式记账则是交易的双方都需要记录本次交易。 一笔交易在交易两方分别记了一次，以交易额的转移方向为箭头，流出就从出账户余额减去交易额，流入就从入账户余额增加交易额。

在Beancount中

[stem#eq1]
++++
(Income + Liabilities) + (Assets + Expenses) + Equity = 0。
++++

为什么全是加法，因为数值本身是有符号的。对于一个交易，其实负数的账目就相当于 “贷”，正数的账目就相当于 “借”。

如果把交易中的负数账目归为一类，正数账目归为一类，不难看出：负数账目意味着这笔交易的金额 “从哪儿来”，而正数账目意味着金额要 “到哪儿去”。

- 资产(Assets): 记录你当前所持有的钱，或者通过交易可以变为钱东西。常见的比如各种银行的存款账户、兜里的现金、车子、房产等等。别人欠你的钱（应收账款）和你欠别人的钱（负债）都是你的资产。
- 负债(Liabilities): 你欠别人的钱。别人的钱现在是在你的兜里，在没有还回去之前，你可以自己决定怎么花，所以也是你的资产。
- 支出(Expenses): 你花出去的钱，而且是花出去之后不会在回来了。常见的如花钱买商品，买服务等。不退款或者退款的前提下，这部分钱就是别人的了。
- 收入(Income): 你得到的钱，得到之后还不用还回去的。比如常见的你劳动所得的工资，你投资的收益，股票的分红等。
- 权益(Equity): 根据会计恒等式，权益本来是资产净值，细分之后理解为资产净值的初始值，也就是记账周期开始时的资产净值。

== 账户主体

每个账户的所有者是谁？重要不，不重要，因为最终看的是

== 账户分类

=== 余额与差额

账户之间最明显的一个区别是：我们到底想知道一个账户的余额，还是它的差额。比方说对于支付宝余额、信用卡欠款，我们更在意现在钱包还有多少钱，因此余额比起差额来说应该更加重要。而对于餐厅账户来说，比起了解这辈子到底花了多少钱吃饭，这个月到底花了多少才更具指导意义，因此对它来说差额又更加重要。

|===
||正数|负数
|更关注 *余额*（资产表）|资产(Assets)|负债(Liabilities)
|更关注 *差额*（损益表）|支出(Expenses)|收入(Income)
|===

=== 位置与目的

账户还可以区分钱在哪(Location)和钱用来干什么了(Purpose)。

|===
|L/P 2+^|账号类型 |报表
|位置(Location)|资产|负债|资产负债表
|目的(Purpose)|收入|支出|损益表
|===

== 参考

* Peter Selinger, Tutorial on multiple currency accounting, https://www.mathstat.dal.ca/~selinger/accounting/tutorial.html
* Martin Blais, The Double-Entry Counting Method, https://beancount.github.io/docs/the_double_entry_counting_method.html
* 复式记账指北（一）：What and Why？ , https://blog.kaaass.net/archives/1659
* Martin Kleppmann, Accounting for Computer Scientists, https://martin.kleppmann.com/2011/03/07/accounting-for-computer-scientists.html